site_name: UAVcast-Pro
theme_dir: docstheme/material
site_url: https://docs.uavmatrix.com/
site_favicon: 'images/favicon.ico'
extra_css:
    - pages/style.css

authors:
    - Bernt Christian Egeland

nav:
    - index.md
    - hardware.md
    - installation.md
    - Pages:
            - 'pages/Dashboard.md'
            - 'pages/Flight-Controller.md'
            - 'pages/Ground-Control.md'
            - 'pages/Cell-Modem.md'
            - 'pages/Dynamic-DNS.md'
            - 'pages/Camera.md'
            - 'pages/Vpn.md'
    - Developers:
                - developers/restapi.md
                - developers/translation.md
    - license/license.md
    - troubleshooting.md
    - application-update.md
    - changelog.md

custom_theme:
    main.html
google_analytics:
  - 'UA-59911815-6'
  - 'auto'
theme:
        name: null
        custom_dir: 'docstheme/material'
        favicon: 'images/favicon.ico'
        language: 'en'
        palette:
                primary: 'indigo'
                accent: 'indigo'
        font:
                text: 'Roboto'
                code: 'Roboto Mono'
        logo:
            icon: 'airplanemode_active'
        feature:
            tabs: false

repo_name: 'uavmatrix/uavcast-pro-docs'
repo_url: https://github.com/UAVmatrix/uavcast-pro-docs/
markdown_extensions:
  - admonition
  - codehilite:
      guess_lang: false
  - toc:
      permalink: "¶"
# Copyright
# copyright: 'Copyright &copy; 2018 - 2019 Bernt Christian Egeland'
